### ISSUE TITLE
需要指定的node版本吗?运行报错

### ISSUE THREAD

**Issue by CY-Christin** [chavyleung/boxts#1]
环境 ubuntu 21.04
nodejs --version  v12.21.0  
运行所有命令都是报下面 这个错
```
jable -h                                             root@google2
/usr/local/lib/node_modules/@boxts/crawler/bin/jable.js:4248
  const [rawSize, unit] = ($size === null || $size === void 0 ? void 0 : $size.split(' ')) ?? ['0', 'GiB'];
                                                                                            ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47

```

**Comment by chavyleung** [comment]
```bash
npm i -g @boxts/crawler@1.0.0-alpha.30
```

更新一下再试试

**Comment by ch634421335** [comment]
> ```shell
> npm i -g @boxts/crawler@1.0.0-alpha.30
> ```
> 
> 更新一下再试试

现在又报这个错了，我在网上搜也没有搜到如何安装缺失的包
```
➜  ~ jable /hot/ -m -l
🔔 /hot/video_viewed_today 🔔
(node:3082035) UnhandledPromiseRejectionWarning: browserType.launch: Host system is missing dependencies!

  Missing libraries are:
      libenchant.so.1
      libicui18n.so.66
      libicuuc.so.66

    at Object.usePlaywright (/usr/local/lib/node_modules/@boxts/crawler/bin/jable.js:4037:43)

```

**Comment by chavyleung** [comment]
运行在什么操作系统下？

**Comment by chavyleung** [comment]
```bash
npx playwright install-deps
```

试试
来源: https://github.com/microsoft/playwright/pull/7796#pullrequestreview-714352883

**Comment by ch634421335** [comment]
> ```shell
> npx playwright install-deps
> ```
> 
> 试试
> 来源: [microsoft/playwright#7796 (review)](https://github.com/microsoft/playwright/pull/7796#pullrequestreview-714352883)

执行后无效 和上面报错一样

**Comment by chavyleung** [comment]
在 ubuntu 21.04 下，需要安排这两个依赖

```bash
cd ~/Downloads
wget http://mirrors.kernel.org/ubuntu/pool/main/i/icu/libicu66_66.1-2ubuntu2_amd64.deb
wget http://mirrors.kernel.org/ubuntu/pool/universe/e/enchant/libenchant1c2a_1.6.0-11.3build1_amd64.deb

sudo dpkg -i libicu66_66.1-2ubuntu2_amd64.deb
sudo dpkg -i libenchant1c2a_1.6.0-11.3build1_amd64.deb
```

来源: https://github.com/microsoft/playwright/issues/4236#issuecomment-855282593

**Comment by ch634421335** [comment]
> 在 ubuntu 21.04 下，需要安装这两个依赖
> 
> ```shell
> cd ~/Downloads
> wget http://mirrors.kernel.org/ubuntu/pool/main/i/icu/libicu66_66.1-2ubuntu2_amd64.deb
> wget http://mirrors.kernel.org/ubuntu/pool/universe/e/enchant/libenchant1c2a_1.6.0-11.3build1_amd64.deb
> 
> sudo dpkg -i libicu66_66.1-2ubuntu2_amd64.deb
> sudo dpkg -i libenchant1c2a_1.6.0-11.3build1_amd64.deb
> ```
> 
> 来源: [microsoft/playwright#4236 (comment)](https://github.com/microsoft/playwright/issues/4236#issuecomment-855282593)

此方法已解决问题，可以正常使用。非常感谢！
